[project]
name = "city-ride-demand"
version = "0.1.0"
description = ""
authors = [
    {name = "Saleh",email = "smalsharideh1@sheffield.ac.uk "}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"
pre-commit = "^4.2.0"
pytest = "^8.4.1"

